Suggesting rmarkdown
```
 creating vignettes ... ERROR
--- re-building ‘MetaboAnnotation.Rmd’ using rmarkdown
Error: processing vignette 'MetaboAnnotation.Rmd' failed with diagnostics:
The 'rmarkdown' package should be declared as a dependency of the 'MetaboAnnotation' package (e.g., in the  'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building ‘MetaboAnnotation.Rmd’
```